### ISSUE TITLE
format 语法

### ISSUE THREAD

**Issue by muzea** [muzea-demo/random-data#5]
允许重写一个约束渲染时候的 `template`

语法

format varName template

比如

```text
constraint w int 1 10
constraint g graph graphNum nodeNum edgeNum
format g ${value[0]} ${value[1]} ${w}
```

这样可以实现有权图，目前这个语法主要用来扩展 `graph` 类型

## 影响

这个信息会挂在到约束上面

因为 `stringify` 的时候是没有 `format` 信息的，所以这里

## todo

- [ ] 如果数据挂在到约束上面 (现在的 `shuffle`) 那么多 `store` 的设计会有问题，需要修改
- [ ] 如果不挂到约束上面，可能需要重新设计几个模块交互的api `rawTemplate` `rawValue`
- [ ] 求值顺序 对于一个 `graph` 来说，是求完所有的边再取 `format` 计算，还是一条边算完 `format` 再算下一条边
